### ISSUE TITLE
MAN 3 Malang was renamed to MAN 2 Kota Malang

### ISSUE THREAD

**Issue by prabowo02** [ia-toki/osn-web#9]
The school [MAN 3 Malang](https://osn.toki.id/statistik/sekolah/384) before the year 2018 is the same as [MAN 2 Kota Malang](https://osn.toki.id/statistik/sekolah/3) from the year 2018 onwards.

The name of the school was renamed in 2018, and they are the same school.
Should we merge these two schools on the web ranking?

**Comment by fushar** [comment]
Terima kasih laporannya. Kedua sekolah sudah disatukan.
